# Generated by Django 6.0.7 on 2026-07-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name_en', models.CharField(default='Tiera & Cielo Agro', max_length=200)),
                ('office_name_hi', models.CharField(default='टिएरा एंड सिएलो एग्रो', max_length=200)),
                ('address_en', models.TextField(blank=True, help_text='Full office/farm address in English')),
                ('address_hi', models.TextField(blank=True, help_text='पता हिंदी में')),
                ('latitude', models.DecimalField(decimal_places=6, default=29.0588, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=76.0856, max_digits=9)),
                ('phone_primary', models.CharField(help_text='Shown as click-to-call button', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits only with country code, e.g. 91XXXXXXXXXX', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, help_text='Square logo. Used in header, browser tab icon, and splash animation.', null=True, upload_to='site/')),
                ('tagline_en', models.CharField(blank=True, help_text='Short line shown under the logo on load', max_length=200)),
                ('tagline_hi', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings (edit the one entry)',
            },
        ),
    ]
