# Generated by Django 6.0.7 on 2026-07-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_hi', models.CharField(max_length=100)),
                ('icon_emoji', models.CharField(blank=True, help_text='Optional emoji shown next to the category, e.g. 🌱', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_hi', models.CharField(max_length=150)),
                ('short_description_en', models.CharField(blank=True, help_text="One short farmer-friendly line, e.g. 'Healthy tomato seedlings, ready to plant'", max_length=160)),
                ('short_description_hi', models.CharField(blank=True, max_length=160)),
                ('description_en', models.TextField(blank=True, help_text='Keep this short — most of the page should be the photo.')),
                ('description_hi', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text="Real photo of the actual seedling/product strongly preferred. If you don't have a photo yet, see 'AI image guidance' below and generate one, then upload it here.", null=True, upload_to='products/')),
                ('ai_image_prompt_used', models.TextField(blank=True, help_text='If this image was AI-generated, paste the prompt you used here for your own records.')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Your listed asking price', max_digits=10)),
                ('unit', models.CharField(choices=[('piece', 'Per Piece / Per Seedling'), ('tray', 'Per Tray'), ('kg', 'Per Kg'), ('dozen', 'Per Dozen'), ('packet', 'Per Packet')], default='piece', max_length=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show near the top of the Products page')),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-is_featured', 'category__order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('village_or_address', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('bid_price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit the customer is offering to pay', max_digits=10)),
                ('message', models.TextField(blank=True, help_text='Any extra note the customer typed')),
                ('status', models.CharField(choices=[('new', 'New — not yet contacted'), ('called', 'Called'), ('confirmed', 'Order Confirmed'), ('not_interested', 'Not Interested / Closed')], default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal notes — call outcome, follow-up date, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Enquiries (Bids)',
                'ordering': ['-created_at'],
            },
        ),
    ]
