# Generated by Django 6.0.7 on 2026-07-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('farm', 'Farm'), ('nursery', 'Nursery')], max_length=10)),
                ('name_en', models.CharField(max_length=150)),
                ('name_hi', models.CharField(max_length=150)),
                ('village_en', models.CharField(blank=True, max_length=120)),
                ('village_hi', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Wide photo of the farm/nursery, used as the card and page banner.', null=True, upload_to='locations/')),
                ('short_description_en', models.CharField(blank=True, max_length=160)),
                ('short_description_hi', models.CharField(blank=True, max_length=160)),
                ('description_en', models.TextField(blank=True)),
                ('description_hi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text="e.g. 'Bed 3' or 'Polyhouse A - Row 2'", max_length=100)),
                ('name_hi', models.CharField(max_length=100)),
                ('crop_name_en', models.CharField(max_length=100)),
                ('crop_name_hi', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, help_text='Current best photo of this bed — shown on the farm page.', null=True, upload_to='beds/')),
                ('sown_date', models.DateField(blank=True, null=True)),
                ('expected_ready_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('prepared', 'Prepared / Not Yet Sown'), ('growing', 'Growing'), ('ready', 'Ready to Sell / Harvest'), ('harvested', 'Harvested / Cleared')], default='growing', max_length=12)),
                ('quantity_available', models.PositiveIntegerField(default=0, help_text="Filled in once status is 'Ready to Sell' — how many units are available")),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='farms.location')),
            ],
            options={
                'ordering': ['-sown_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='progress/')),
                ('date', models.DateField()),
                ('caption_en', models.CharField(blank=True, help_text="e.g. 'First leaves appearing' — keep it short and simple", max_length=160)),
                ('caption_hi', models.CharField(blank=True, max_length=160)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='farms.bed')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
